name = "kundenfeedback-tool"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kundenfeedback-db"
database_id = "8a00c213-dd31-4cea-8622-2a75a601fd51"
